apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: akhq
spec:
  entryPoints:
    - internalhttps
  routes:
    - kind: Rule
      match: {{.Values.akhq.hostPrefixRegex}} && PathPrefix(`/akhq`)
      services:
        - kind: Service
          name: {{ .Release.Name }}-akhq
          namespace: {{ .Release.Namespace }}
          passHostHeader: true
          port: 80