---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-inspector-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-inspector-app
  template:
    metadata:
      labels:
        app: http-inspector-app
    spec:
      containers:
        - image: mendhak/http-https-echo
          imagePullPolicy: Always
          name: http-inspector-app-container
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: http-inspector
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: http-inspector-app